name: Cloud Resume CI/CD
on: push

jobs:
  test-infra:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: test get-function
        run: python -m unittest tests/unit/sum_test.py
      # - name: test put-function
      #   run: cd cloud-resume-challenge/put-function/app.py
      # - run: python my_script.py

# name: CI/CD Backend Cloud Resume
# on:
#   push:        
#     paths:
#     - 'Lambda/*'
#     - 'template.yaml'
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@master
      
#       - uses: actions/checkout@v2
#       - name: Set up Python 3.8
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.8
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install  pytest
#           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 